INSERT INTO `bookshop`.`books`(`title`,`author`,`category`) VALUES ('Krzyżacy','Henryk Sienkiewicz','literatura szkolna')
INSERT INTO `bookshop`.`books`(`title`,`author`,`category`) VALUES ('Ogniem i mieczem','Henryk Sienkiewicz','literatura szkolna')
INSERT INTO `bookshop`.`books`(`title`,`author`,`category`) VALUES ('Potop','Henryk Sienkiewicz','literatura szkolna')
INSERT INTO `bookshop`.`books`(`title`,`author`,`category`) VALUES ('fawefa','Henryk Sienkiewicz','fantakstyka')
INSERT INTO `bookshop`.`books`(`title`,`author`,`category`) VALUES ('ewfa','Henryk Sienkiewicz','fantastyka')
INSERT INTO `bookshop`.`books`(`title`,`author`,`category`) VALUES ('fewafewa','Henryk Sienkiewicz','fantastyka')
INSERT INTO `bookshop`.`books`(`title`,`author`,`category`) VALUES ('chacy','Henryk Sienkiewicz','literatura szkolna')
INSERT INTO `bookshop`.`books`(`title`,`author`,`category`) VALUES ('Ogniem i woda','Henryk Sienkiewicz','literatura szkolna')
INSERT INTO `bookshop`.`books`(`title`,`author`,`category`) VALUES ('Ogniotop','Henryk Sienkiewicz','literatura szkolna')
INSERT INTO `bookshop`.`books`(`title`,`author`,`category`) VALUES ('fafewaefawefa','Henryk Sienkiewicz','fantakstyka')
INSERT INTO `bookshop`.`books`(`title`,`author`,`category`) VALUES ('ewa','Henryk Sienkiewicz','fantastyka')
INSERT INTO `bookshop`.`books`(`title`,`author`,`category`) VALUES ('flewa','Henryk Sienkiewicz','fantastyka')
INSERT INTO `bookshop`.`user_role`(`role`,`description`) VALUES ('ROLE_USER','default role for user')
INSERT INTO `bookshop`.`user_role`(`role`,`description`) VALUES ('ROLE_MODERATOR','shop managment')
INSERT INTO `bookshop`.`user_role`(`role`,`description`) VALUES ('ROLE_ADMINISTRATOR','global managment')